name: 测试流程C
description: 这是一个测试流程C
steps:
  - name: 步骤0
    file: home.xml
    description: 这是Home
  - name: 步骤1
    file: step1.xml
    description: 这是步骤1
  - name: 步骤2
    file: step2.xml
    description: 这是步骤2
  - name: 步骤3
    file: step3.xml
    description: 这是步骤3

