name: 测试流程0
description: 这是一个测试流程0
steps:
  - name: 步骤0
    file: home.xml
    description: 这是Home
  - name: 步骤1
    file: xzsg-begin.xml
    description: 这是步骤1
  - name: 步骤2
    file: xzsg-step0.xml
    description: 这是步骤2
  - name: 步骤2.1
    file: xzsg-step0a.xml
    description: 这是步骤2.1
  - name: 步骤2.2
    file: xzsg-step0b.xml
    description: 这是步骤2.2
  - name: 步骤3
    file: xzsg-step1.xml
    description: 这是步骤3
  - name: 步骤4
    file: xzsg-step2.xml
    description: 这是步骤4
  - name: 步骤5
    file: xzsg-zend.xml
    description: 这是步骤5

